ui: tape
browsers:
  - name: internet explorer
    version: 6..latest
  - name: chrome
    version: 26..latest
  - name: firefox
    version: 4..latest
  - name: safari
    version: 5..latest
  - name: iphone
    version: '5.1..latest'
  - name: android
    version: '4.0..latest'
  - name: opera
    version: 11..latest
  - name: ipad
    version: '5.1..latest'
  - name: microsoftedge
    version: 20..latest
